### PR TITLE
Testing a different UI

### PR DESCRIPTION
**Pull request by DivergentEuropeans**
So from:

image

to:

(see below comment)

For full discussion, go to: 
https://gitlab.com/divergenteuropeans/loser-simulator/-/merge_requests/5

### CODE REVIEW

**Comment by DivergentEuropeans** [comment]
Most recent version! @Priyansh61 Should have addressed most of your comments!

image

**Comment by DivergentEuropeans** [comment]
Updated tutorials:

image

image

image

**Comment by DivergentEuropeans** [comment]
- different UI
- added dialogue options
- fixed tutorials

**Comment by DivergentEuropeans** [comment]
new UI:  

image

**Review by Priyansh61 — COMMENTED** [review]
image

I dont know but the navbar buttons dont directly work, they redirect the user toward the left panel.


image

The color here of the text makes it impossible to read

image


The icon next to advice has very few contrast ratio...

image

Overlapping money with the status bars


- The icon next to text problem is at many places since the icons are suited to light bgs but now due to darker colors they are really difficult to understand what are they meant for?

- Yeah!!! the above problem is there at almost every place so we can either invert the color of all the dark icons

image


Should we present the user with 3 locked tiles or should we just have 1 locked tile everytime and that tile gets unlocked over the time you progress in the game, IG this UX would be much better.

**Comment by DivergentEuropeans** [comment]
Ok, check it out @Priyansh61 

image

- Better color for icons
- Better padding for text fields, +fixed positioning and color for text
- Better background

**Comment by Priyansh61** [comment]
@DivergentEuropeans LGTM :)

**Pull request merged**
